POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json

{
    "username":"amin",
    "email":"amin.mail.com",
    "password":"123321",
    "role":"admin"
}

###
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json

{
    "email": "sayeed@.com",
    "password": "123321"
}

###
POST http://localhost:3000/admin/addproduct HTTP/1.1
Content-Type: application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InNheWVlZCIsImVtYWlsIjoic2F5ZWVkQGdtYWlsLmNvbSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNjk4NTIxNzgwLCJleHAiOjE2OTg1MjI2ODB9.TOGBusI3JiCI8WDGDnPudN2IKuFENt_cDxfBkMKMDJk",
     "name":"Galaxy F12",
    "brand":"samsung",
    "price":20000,
    "status":"Available"
}

